In [1]:
import numpy as np
import pandas as pd

In [21]:
# 1) Generate an array of zeroes using inbuit numpy function.
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# 2) Run the given code and find the dot product of both arrays.
a = np.random.randint(2,10,(3,4))
b = np.random.randint(2,10,(4,3))
print(a)
print(b)

[[7 9 3 4]
 [8 5 9 4]
 [7 9 8 5]]
[[3 7 4]
 [3 3 4]
 [4 3 2]
 [2 7 6]]


In [24]:
a.dot(b)

array([[ 68, 113,  94],
       [ 83, 126,  94],
       [ 90, 135, 110]])

In [25]:
b.dot(a)

array([[105,  98, 104,  60],
       [ 73,  78,  68,  44],
       [ 66,  69,  55,  38],
       [112, 107, 117,  66]])

# 3)Read the csv file provided using pandas and display the first 5 entries

In [6]:
data = pd.read_csv('/Users/musubimanagement/Downloads/techis-ds-wiki-master/Step 1-4 Data Processing/03_Assignment/data.csv')

In [7]:
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

# 4)Describe the data with all features.

In [8]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.3+ KB


# 5)Find the total count of missing values for each feature. 

In [10]:
data.isna().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

# 6)Display all the unique values from the 'DESCRIPTION’ column.

In [11]:
data['DESCRIPTION'].unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [12]:
data['DESCRIPTION'].nunique()

5

In [13]:
data['DESCRIPTION'].value_counts()

State Park               13
State Recreation Area     7
State Nature Preserve     2
State Natural Area        2
Interpretive Center       1
Name: DESCRIPTION, dtype: int64

# 7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [14]:
grp_tbl = data.groupby('DESCRIPTION').mean()
grp_tbl

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [15]:
grp_tbl.head()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

# 8)Generate a random sample of 10 rows from the data.

In [16]:
df = data.sample(n=10)
df

OBJECTID                              UNIT_NAME            DESCRIPTION  \
18        39        Gunlogson State Nature Preserve  State Nature Preserve   
3         24                 Fort Ransom State Park             State Park   
20        41      Missouri River State Natural Area     State Natural Area   
11        32                 Sully Creek State Park             State Park   
6         27              Lake Metigoshe State Park             State Park   
1         22                 Beaver Lake State Park             State Park   
13        36  Crow Flies High State Recreation Area  State Recreation Area   
10        31             Little Missouri State Park             State Park   
22        44  Turtle Mountain State Recreation Area  State Recreation Area   
17        38    Fahlgren Park State Recreation Area  State Recreation Area   

      ACRES  SHAPE.AREA  SHAPE.LEN  
18    95.89    0.000048   0.040465  
3    933.78    0.000444   0.128733  
20   174.39    0.000083   0.087192  
11    63.03    0.000030   0.024016  
6   1508.53    0.000751   0.212196  
1    273.16    0.000129   0.080067  
13   247.11    0.000120   0.050518  
10  6492.93    0.003136   0.313756  
22   695.04    0.000345   0.086487  
17    21.56    0.000010   0.013294

# 9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [19]:
data['New_feature'] = np.random.rand(25)
data['New_feature']

0     0.493088
1     0.144489
2     0.653136
3     0.803490
4     0.801173
5     0.027288
6     0.935114
7     0.751969
8     0.395980
9     0.563742
10    0.293021
11    0.354852
12    0.344849
13    0.680821
14    0.125683
15    0.987120
16    0.254838
17    0.472603
18    0.343547
19    0.041251
20    0.139109
21    0.950239
22    0.919685
23    0.019025
24    0.455126
Name: New_feature, dtype: float64

# 10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [18]:
data['OBJECTID'] = data['OBJECTID'].replace(0,data["OBJECTID"].mean())
data['OBJECTID']

0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64

In [20]:
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  New_feature  
0              State Park   586.48    0.000284   0.135641     0.493088  
1              State Park   273.16    0.000129   0.080067     0.144489  
2              State Park   836.47    0.000399   0.119868     0.653136  
3              State Park   933.78    0.000444   0.128733     0.803490  
4              State Park   959.33    0.000469   0.125546     0.801173  
5              State Park   930.30    0.000461   0.166712     0.027288  
6              State Park  1508.53    0.000751   0.212196     0.935114  
7              State Park   524.81    0.000256   0.130420     0.751969  
8     Interpretive Center    14.71    0.000007   0.016774     0.395980  
9   State Recreation Area    11.40    0.000005   0.009396     0.563742  
10             State Park  6492.93    0.003136   0.313756     0.293021  
11             State Park    63.03    0.000030   0.024016     0.354852  
12  State Recreation Area    51.23    0.000025   0.022095     0.344849  
13  State Recreation Area   247.11    0.000120   0.050518     0.680821  
14             State Park   775.28    0.000378   0.145220     0.125683  
15             State Park   739.52    0.000357   0.191806     0.987120  
16     State Natural Area   264.84    0.000127   0.067082     0.254838  
17  State Recreation Area    21.56    0.000010   0.013294     0.472603  
18  State Nature Preserve    95.89    0.000048   0.040465     0.343547  
19  State Nature Preserve    72.30    0.000034   0.033885     0.041251  
20     State Natural Area   174.39    0.000083   0.087192     0.139109  
21  State Recreation Area  1236.98    0.000615   0.338800     0.950239  
22  State Recreation Area   695.04    0.000345   0.086487     0.919685  
23             State Park   569.07    0.000274   0.180257     0.019025  
24  State Recreation Area    25.22    0.000013   0.026357     0.455126